services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8080
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - PORT=${PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_SECONDS_TO_EXPIRATION=${JWT_SECONDS_TO_EXPIRATION}
    depends_on:
      firestore_emulator:
        condition: service_healthy
  firestore_emulator:
    image: 'andreysenov/firebase-tools'
    command: >
      firebase emulators:start
      --only firestore
      --project ${FIRESTORE_PROJECT_ID}
      --import=/data/latest
      --export-on-exit=/data/latest
    ports:
      - ${FIRESTORE_EMULATOR_PORT}:8080
    volumes:
      - ./firebase.json:/home/node/firebase.json
      - ./firestore-data:/data
    healthcheck:
      test: ['CMD', 'node', '-e', "require('http').get('http://localhost:8080', r => process.exit(r.statusCode < 500 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes: {}
